spring:
  application:
    name: et-bff-service

server:
  port: 8085

services:
  et-uas:
    name: et-user-auth-service
    url : http://et-uas:8081/api

  et-es:
    name: et-expense-service
    url: http://et-es:8082/api

  et-rs:
    name: et-reports-service
    url: http://et-rs:8083/api
    